executor: slurm

default-resources:
  slurm_partition: defq
  mem_mb: 8000
  runtime: 120        # minutes; defq default is 120, max is 90 days

jobs: 100
use-conda: true
conda-prefix: /isilon/datalake/sprockett_lab/original/WF00SprockettLab/envs/snakemake_envs

set-resources:
  host_filter:
    mem_mb: 16000
    runtime: 480
  megahit:
    runtime: 480
  metaphlan:
    mem_mb: 32000
    runtime: 240
  taxonomy_kraken:
    mem_mb: 220000
    runtime: 240
latency-wait: 60
rerun-incomplete: true
keep-going: true
printshellcmds: true
